from server import TOTAL_COUNT

SECONDS_PER_HOUR = 3600
SECONDS_PER_DAY = 3600 * 24
SECONDS_PER_WEEK = 3600 * 24 * 7
HOUR_INTERVAL = SECONDS_PER_HOUR / TOTAL_COUNT
DAYS_INTERVAL = SECONDS_PER_DAY / TOTAL_COUNT
WEEK_INTERVAL = SECONDS_PER_WEEK / TOTAL_COUNT
